/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import mastermind.Peli;
import mastermind.Tulokset.Tulos;

/**
 *
 * @author katri
 */
public class Kayttoliittyma extends javax.swing.JFrame {
    private Peli peli;
    /**
     * Creates new form Kayttoliittyma
     */
    final char SMILEFACE = '\u263a';
    final char SNOWFLAKE = '\u2744';
    final char ROSETTE = '\u2740';
    final char BLACKSTAR = '\u2605';
    final char FISHEYE = '\u25c9';
    final char AIRPLANE = '\u2708';
    final char HOURGLASS = '\u231b';
    final char TELEPHONE = '\u260e';
    final char SCISSORS = '\u2702';
    final char WHITEFLAG = '\u2690';
    final char CIRCLE = '\u25cf';
    final char BOX = '\u25a0';
    final char KEYBOARD = '\u2328';
    final char SKULL = '\u2620';
    final char YING = '\u262f';
    final char BLACKDIAMOND = '\u2756';
    final char CIRCLESTAR = '\u272a';
    final char ARROW = '\u2794';
    final char CHECKMARK = '\u2611';
    
    private char merkki;
    private int vareja;
    private final UusiPeliDialog uusiPeliDialog;
    private Tulokset tulokset;
    private String pelaaja;
    
    
    private void alustaCombo(JComboBox c) {
        c.removeAllItems();
        for(int i=1; i<=vareja; i++) {
            c.addItem(""+i);
        }
        Renderoija renderer = new Renderoija(merkki);
        c.setPreferredSize(new Dimension(10, 10));
        c.setRenderer(renderer);
        
    }
    
    public Kayttoliittyma() {
        tulokset = new Tulokset("parhaat.txt");
        initComponents();
        pelaaja = "";
        ArrayList<Character> merkit = new ArrayList<Character>();
        merkit.add(SMILEFACE);
        merkit.add(SNOWFLAKE);
        merkit.add(ROSETTE);
        merkit.add(BLACKSTAR);
        merkit.add(FISHEYE);
        merkit.add(AIRPLANE);
        merkit.add(HOURGLASS);
        merkit.add(TELEPHONE);
        merkit.add(SCISSORS);
        merkit.add(WHITEFLAG);
        merkit.add(CIRCLE);
        merkit.add(BOX);
        merkit.add(KEYBOARD);
        merkit.add(SKULL);
        merkit.add(YING);
        merkit.add(BLACKDIAMOND);
        merkit.add(CIRCLESTAR);
        merkit.add(CHECKMARK);
        JOptionPane.showMessageDialog(this, "Tervetuloa pelaamaan MasterMind peliä!\nOle hyvä ja valitse haluamasi värimäärä (1-10) sekä näytettävä merkki.", "MasterMind", JOptionPane.PLAIN_MESSAGE);
    
        uusiPeliDialog = new UusiPeliDialog(this, true, merkit);
        uusiPeli();
    }
    
    private void uusiPeli() {
        uusiPeliDialog.setVisible(true);
        merkki = uusiPeliDialog.haeMerkki();
        vareja = uusiPeliDialog.haeVareja();
        peliPanel.asetaMerkki(merkki);
        peli = new Peli(vareja,10);
        alustaCombo(arvausCombo1);
        alustaCombo(arvausCombo2);
        alustaCombo(arvausCombo3);
        alustaCombo(arvausCombo4);
        peliPanel.asetaRivit(null);
        peliPanel.repaint();
    }        
    
    private void naytaParhaat() {
        String s = "";
        for(Tulos t : tulokset.haeLista(vareja)) {
            s = s + t.haeNimi() + " " + t.haeArvauksia() + "\n";
        }
        if(s.length() == 0) {
            s = "ei tuloksia";
        }
        
        JOptionPane.showMessageDialog(this, s,"Parhaat tulokset",JOptionPane.PLAIN_MESSAGE);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        arvausCombo1 = new javax.swing.JComboBox();
        arvausCombo2 = new javax.swing.JComboBox();
        arvausCombo3 = new javax.swing.JComboBox();
        arvausCombo4 = new javax.swing.JComboBox();
        arvaaButton = new javax.swing.JButton();
        peliPanel = new mastermind.PeliPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        arvausCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        arvausCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvausCombo1ActionPerformed(evt);
            }
        });

        arvausCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        arvausCombo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        arvausCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvausCombo3ActionPerformed(evt);
            }
        });

        arvausCombo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        arvaaButton.setText("Arvaa");
        arvaaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvaaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout peliPanelLayout = new javax.swing.GroupLayout(peliPanel);
        peliPanel.setLayout(peliPanelLayout);
        peliPanelLayout.setHorizontalGroup(
            peliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        peliPanelLayout.setVerticalGroup(
            peliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Peli");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Uusi peli");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText("Ohje");

        jMenuItem1.setText("Ohjeet");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arvausCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arvausCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arvausCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arvausCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(arvaaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(peliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 335, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(peliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arvausCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvausCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvaaButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void arvaaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvaaButtonActionPerformed
        ArrayList<Integer> arvaus = new ArrayList<Integer>();
        arvaus.add(arvausCombo1.getSelectedIndex());                
        arvaus.add(arvausCombo2.getSelectedIndex());
        arvaus.add(arvausCombo3.getSelectedIndex());
        arvaus.add(arvausCombo4.getSelectedIndex());
        TarkastusTulos tulos = peli.arvaus(arvaus);
        peliPanel.asetaRivit(peli.haeArvatutRivit());
        peliPanel.repaint();
        if(tulos.haeKaikkiOikein()) {
            if(tulokset.mahtuuko(vareja, peli.haeArvauksia())) {
                pelaaja = JOptionPane.showInputDialog("Oikein arvattu! Pääsit listalle, anna nimesi", pelaaja);                
                tulokset.lisaa(vareja, peli.haeArvauksia(), pelaaja);
            }
            else {
                JOptionPane.showMessageDialog(this, "Oikein arvattu!");
  
            }
            naytaParhaat();
            uusiPeli();
        }
        else if(peli.haeArvauksia() == 10) {
            ArrayList<Arvaus> rivi = peli.haeArvatutRivit();
            rivi.add(new Arvaus(peli.haeOikeaRivi(), new TarkastusTulos(4,0,true)));
            peliPanel.asetaRivit(rivi);
            peliPanel.repaint();
            JOptionPane.showMessageDialog(this, "Valitettavasti arvausyritykset loppuivat");
            naytaParhaat();
            uusiPeli();
        }
       
    }//GEN-LAST:event_arvaaButtonActionPerformed

    private void arvausCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvausCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arvausCombo1ActionPerformed

    private void arvausCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvausCombo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arvausCombo3ActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        uusiPeli();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, 
         "Pelin ideana on arvailla toisen (koneen) arpomaa riviä,\n"+
         "mikä koostuu eri värisistä merkeistä. Paikkoja on neljä ja\n"+
         "värejä valinnan mukaan 1-10, jonka lisäksi voi pelata eri\n"+
         "näköisillä merkeillä. Ohjelma arpoo ensin rivin ja pistää\n"+
         "käyttäjää arvailemaan sitä. Käyttäjällä on enintään kymmenen\n"+
         "arvausta. Jokaiselle arvaukselle ohjelma vastaa antamalla\n"+
         "valkoisen \"merkin\" jokaista sellaista merkkiä kohden,\n"+
         "joka on oikean värinen, mutta väärällä paikalla kertomatta\n"+
         "tarkalleen mikä väreistä oli oikea ja mikä väärä.\n"+
         "Jokaista oikealla paikalla olevaa ja oikean väristä\n"+
         "merkkiä kohden kone antaa vihjeenä mustan \"merkin\".\n"+
         "Ohjelma näyttää ruudulla vanhat arvaukset, joiden\n"+
         "perusteella käyttäjä voi tehdä uuden arvauksen."               
                , "Ohjeet", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arvaaButton;
    private javax.swing.JComboBox arvausCombo1;
    private javax.swing.JComboBox arvausCombo2;
    private javax.swing.JComboBox arvausCombo3;
    private javax.swing.JComboBox arvausCombo4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private mastermind.PeliPanel peliPanel;
    // End of variables declaration//GEN-END:variables
}
